export interface Location {
    city_location: string,
    'search term': string,
    id: string,
    alias: string,
    name: string,
    rating: string,
    review_count: string,
    price: string,
    phone: string,
    categories: string,
    latitude: string,
    longitude: string,
    display_address: string,
    city: string,
    state: string,
    zip_code: string,
    url: string,
    price_level: unknown | number
}